### ISSUE TITLE
Bug in color choice

### ISSUE THREAD

**Issue by Pechenux** [Haz001/PyDraw#1]
**Describe the bug**
Error in color choice 

**To Reproduce**
1. Run code
2. Click 1px below purple color

**Expected behavior**
Nothing

**Screenshots**
![Bug in gif](https://user-images.githubusercontent.com/26878278/58379207-4a609900-7fba-11e9-9b5d-d77f35b89df8.gif)

**Desktop:**
 - OS: Windows 10
 - Python version 3.7.3

**Comment by Haz001** [comment]
This bug has been fixed and a new release has been made 'v0.0.3-alpha'.
Thanks for finding and reporting this.
